In [1]:
!pip install -U scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 19.2 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2


In [2]:
import numpy as np
from sklearn.decomposition import NMF

# Generate a random matrix A (replace this with your data)
A = np.random.randint(10, 100, size=(5, 5))
print(A)


[[73 35 56 52 55]
 [84 51 83 89 85]
 [50 78 41 45 74]
 [68 96 97 60 37]
 [48 47 12 86 84]]


In [3]:

# Initialize the NMF model
nmf_model = NMF(n_components=5, init='random', random_state=0)

# Fit the model to your data
nmf_model.fit(A)

# Get the components (H)
H = nmf_model.components_.T

In [4]:
H

array([[ 3.87157886,  2.59125242,  2.21266088,  2.3002543 , 10.87129884],
       [ 0.01152691,  4.49976886,  6.19690522,  4.00417549,  3.61251048],
       [ 2.21042985,  4.15962709,  4.69628953,  0.        , 10.8663946 ],
       [10.00891697,  0.        ,  1.87813074,  2.6964382 ,  0.62712473],
       [ 7.54605652,  3.66000002,  0.        ,  3.66771796,  2.29263837]])

In [5]:
print(H)

[[ 3.87157886  2.59125242  2.21266088  2.3002543  10.87129884]
 [ 0.01152691  4.49976886  6.19690522  4.00417549  3.61251048]
 [ 2.21042985  4.15962709  4.69628953  0.         10.8663946 ]
 [10.00891697  0.          1.87813074  2.6964382   0.62712473]
 [ 7.54605652  3.66000002  0.          3.66771796  2.29263837]]


In [6]:
W = nmf_model.fit_transform(A)

In [7]:


 print(W)

[[ 3.63962488  0.          0.          4.74868857  4.41357947]
 [ 7.96460896  4.14954966  2.92441298  0.66914647  3.16501893]
 [ 1.79543918  7.40037597  1.33167827  9.0972045   0.        ]
 [ 3.39559777  1.73729071 12.98918717  0.14480218  1.95730127]
 [ 5.43418036  0.          0.         11.72205424  0.        ]]


In [8]:
import numpy as np
X = np.array([[1, 1], [2, 1], [3, 1.2], [4, 1], [5, 0.8], [6, 1]])
from sklearn.decomposition import NMF
model = NMF(n_components=2, init='random', random_state=0)
W = model.fit_transform(X)
H = model.components_t

AttributeError: 'NMF' object has no attribute 'components_t'

In [ ]:
W

In [ ]:
H